version: "3"
services:
    solr:
        image: solr
        ports:
            - "8983:8983"
        volumes:
            - ./data:/opt/solr/server/solr/informationRetrieval
            - ./solr-data:/solr-8.11.2
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - mycore
volumes:
    data:
